app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/spark/android/SparkApplication.kt, app/src/main/java/com/spark/android/ui/base/BaseActivity.kt, app/src/main/java/com/spark/android/ui/base/BaseFragment.kt, app/src/main/java/com/spark/android/utill/BindingAdapters.kt, build.gradle
=> #1 [chore] 초기세팅

app/src/main/res/values/colors.xml
=> [chore] color 추가

app/src/main/res/layout/activity_habit.xml, app/src/main/res/layout/item_habit_team.xml, app/src/main/res/values/strings.xml
=> #23 [습관방] 기타 파일 수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt, app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt, app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt, app/src/main/res/layout/activity_join_code.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_make_room.xml
=> #36 [홈_메인] 각버튼 인텐트 추가, fab 백그라운드 클릭 리스너 추가

app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt
=> #36 [홈_메인] fab 배경터치시 fab 닫히지 않도록 수정

app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/namesetting/NameSettingFragment.kt, app/src/main/java/com/spark/android/ui/makeroom/namesetting/viewmodel/NameSettingViewModel.kt, app/src/main/res/drawable/ic_make_room_name_setting_back.xml, app/src/main/res/drawable/shape_btn_inactive.xml, app/src/main/res/layout/activity_make_room.xml, app/src/main/res/layout/fragment_name_setting.xml, app/src/main/res/values/strings.xml
=> #45 [습관방 생성_방이름 설정] 방이름 설정 프래그먼트 만들기

app/src/main/java/com/spark/android/SparkApplication.kt, app/src/main/java/com/spark/android/data/remote/api/FeedService.kt, app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/SignInRepository.kt, app/src/main/java/com/spark/android/data/remote/service/FeedService.kt, app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/signin/SignInFragment.kt, app/src/main/java/com/spark/android/ui/signin/SignInViewModel.kt, app/src/main/res/layout/fragment_sign_in.xml
=> #54 [fix] 카카오계정 로그인 제외 카카오톡 로그인 context 에러 해결

app/src/main/java/com/spark/android/data/remote/service/KakaoLoginService.kt
=> #54 [feat] KakaoLoginService 생성

app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt, app/src/main/java/com/spark/android/ui/joincode/inputcode/viewModel/InputCodeFragmnetDialogViewModel.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt, app/src/main/res/drawable/shape_spark_white_fill_2_rect.xml, app/src/main/res/layout/activity_join_code.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_input_code_dialog.xml, app/src/main/res/layout/fragment_name_setting.xml, app/src/main/res/layout/fragment_select_confirm_method.xml, app/src/main/res/layout/fragment_waiting_room.xml, app/src/main/res/values/strings.xml
=> #58 [방입장_코드 입력] 다이얼로그 프래그먼트 만들기

app/src/main/java/com/spark/android/SparkApplication.kt, app/src/main/java/com/spark/android/data/remote/LocalPreferences.kt, app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt
=> #82 [feat] Hilt 안 쓸 경우 사용할 서버통신 소스 구현

app/src/main/java/com/spark/android/data/remote/service/StorageService.kt, app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
=> #86 [타이머] x버튼, 뒤로가기 버튼, 다이얼로그 붙임

app/src/main/res/layout/activity_timer_start.xml
=> #91 [타이머] 타이머 종료버튼 터치영역 늘림 

app/src/main/AndroidManifest.xml, app/src/main/java/com/spark/android/ui/auth/profile/MultiPartResolver.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInViewModel.kt, app/src/main/java/com/spark/android/ui/profile/ProfileBottomSheet.kt, app/src/main/java/com/spark/android/ui/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/profile/ProfileViewModel.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt, app/src/main/res/layout/bottom_sheet_profile.xml, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/layout/fragment_sign_in.xml, app/src/main/res/navigation/auth_nav_graph.xml
=> #84 [회원가입] 프로필 사진 설정 후 회원가입 구현

app/src/main/java/com/spark/android/data/remote/entity/request/MakeRoomRequest.kt, app/src/main/java/com/spark/android/data/remote/entity/response/MakeRoomResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/MakeRoomService.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt, app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/viewmodel/SelectConfirmMethodViewModel.kt, app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt, app/src/main/res/layout/item_home_recyclerview.xml, app/src/main/res/layout/item_home_recyclerview_waiting.xml, app/src/main/res/values/strings.xml
=> #102 [방 생성] 습관방 생성 네트워크 붙이기 완료

app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt
=> #108 [modify] 인증화면 코드 수정

app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
=> #110 [오늘의 인증] 타이머-사진 인증 연결 수정

app/src/main/res/layout/activity_timer_start.xml, app/src/main/res/layout/bottom_sheet_certify.xml, app/src/main/res/layout/bottom_sheet_habit_more.xml, app/src/main/res/layout/bottom_sheet_habit_send_spark.xml, app/src/main/res/layout/bottom_sheet_habit_today.xml, app/src/main/res/layout/item_habit_team.xml
=> #113 [습관방, 오늘의 인증] 레이아웃 색 변경 및 타이머 버튼 위치 조정

app/src/main/java/com/spark/android/data/remote/entity/response/RefreshResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/RefreshRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/RefreshRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/RefreshService.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
=> #119 [대기방] 인원 목록 새로고침 네트워크 붙였으니 500오류남 (추후 수정)

app/src/main/java/com/spark/android/data/remote/entity/response/NoDataResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/SetPurposeService.kt, app/src/main/java/com/spark/android/data/remote/service/StartHabitService.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
=> #121 [대기방] 습관방 시작 네트워크 붙였으나 500 오류(추후 수정)

app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt, app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt, app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomActivity.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/util/FloatingAnimationUtil.kt, app/src/main/res/layout/fragment_input_code_dialog.xml, app/src/main/res/layout/fragment_waiting_room.xml
=> #124 [전체화면] 기타 오류 및 액티비티간 이동 관계정리, 애니메이션 처리

app/build.gradle, app/src/main/java/com/spark/android/data/remote/entity/response/JoinCodeRoomInfoResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomInfoRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomInfoRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/JoinCodeRoomInfoService.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt, app/src/main/java/com/spark/android/ui/joincode/inputcode/viewModel/InputCodeFragmnetDialogViewModel.kt, app/src/main/res/layout/activity_join_code.xml
=> #123 [습관방 입장] 코드로 대기방 정보확인 네트워크 붙이기

app/src/main/java/com/spark/android/data/remote/entity/response/StorageResponse.kt
=> #130 [보관함] 보관함 미완료 카드 에러 수정

app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/JoinCodeRoomDoneService.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/joincode/data/JoinCodeData.kt, app/src/main/java/com/spark/android/ui/joincode/viewmodel/JoinCodeViewModel.kt
=> #136 [습관방 입장] 습관방 참여 완료

app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/navigation/main_nav_graph.xml
=> #141 [modify] 메인 화면 네비게이션으로 수정

app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt, app/src/main/java/com/spark/android/data/remote/entity/response/PhotoCollectionResponse.kt, app/src/main/java/com/spark/android/data/remote/service/PhotoCollectionService.kt, app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt, app/src/main/java/com/spark/android/ui/storage/StoragePhotoCollectionActivity.kt, app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt, app/src/main/java/com/spark/android/ui/storage/adapter/PhotoCollectionRvAdapter.kt, app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoCollectionViewModel.kt, app/src/main/res/layout/activity_storage_photo_collection.xml, app/src/main/res/layout/item_photo_collection_list.xml
=> #142 [인증사진] 인증사진 모음 서버 붙이기 

app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/res/navigation/main_nav_graph.xml
=> #138 [홈_메인]  홈 메인 새로고침 네비게이션으로 해결

app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/java/com/spark/android/util/ToastMessageUtil.kt, app/src/main/res/navigation/main_nav_graph.xml, app/src/main/res/values/strings.xml
=> #145 [메인] 네비게이션 적용 부분 백스택 관리 및 앱종료 이벤트 설정

app/src/main/res/layout/fragment_home_main.xml, app/src/main/res/layout/item_home_recyclerview.xml
=> #157 [홈_메인] 홈화면 empty view 위치조정 + 글씨 분기처리 조정

app/src/main/java/com/spark/android/data/remote/entity/request/CertifyRequest.kt, app/src/main/java/com/spark/android/data/remote/service/CertifyService.kt, app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt
=> #159 [오늘의 인증] 오늘의 인증 서버 연결

app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/res/layout/fragment_home_main.xml
=> #153 [홈_메인] 로딩 화면 붙이기

app/src/main/java/com/spark/android/data/remote/service/CertifyService.kt, app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt, app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt, app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt, app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
=> #166 [오늘의 인증] 사진 인증 모드 구현

app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/JoinCodeRoomDoneRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/MakeRoomRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/RefreshRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/RefreshRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/SetPurposeRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/StartHabitRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepositoryImpl.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/java/com/spark/android/ui/joincode/viewmodel/JoinCodeViewModel.kt, app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/viewmodel/SelectConfirmMethodViewModel.kt, app/src/main/java/com/spark/android/ui/setpurpose/viewmodel/SetPurposeViewModel.kt, app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
=> #167 [전체화면] 서버 에러처리  (kotlin runcatching)

app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/MakeRoomActivity.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomActivity.kt
=> #172 [전체화면] 스테이터스 바 색상 변경

app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt, app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt, app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt, app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt, app/src/main/res/values/strings.xml
=> #171 [인증, 인스타 공유] 타이머 없는 인증 관련 에러 수정 및 인스타 공유 연결

app/src/main/java/com/spark/android/ui/habit/HabitGoalManageActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/namesetting/NameSettingFragment.kt, app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt, app/src/main/java/com/spark/android/util/EditTextUtil.kt
=> #179 [전체화면] 포커스시 edit text 색상 바꾸기

app/src/main/java/com/spark/android/ui/auth/profile/ProfileBottomSheet.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt, app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/spark/android/ui/certify/CertifyBottomSheet.kt, app/src/main/java/com/spark/android/ui/certify/viewmodel/CertifyViewModel.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt, app/src/main/java/com/spark/android/util/ImageProvider.kt, app/src/main/res/layout/activity_certify.xml, app/src/main/res/layout/fragment_profile.xml
=> [카메라 사용] 사진 화질 높이기

app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt, app/src/main/java/com/spark/android/ui/storage/ZoomOutPageTransformer.kt, app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt
=> [보관함] 보관함 뷰페이저에 애니메이션 추가

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt, app/src/main/java/com/spark/android/util/AnimationUtil.kt, app/src/main/java/com/spark/android/util/KeyBoardUtil.kt, app/src/main/java/com/spark/android/util/KeyboardVisibilityUtils.kt, app/src/main/res/layout/fragment_set_purpose.xml
=> #193 [목표관리] edit text 부분 올라가고 내려가는것 애니메이션으로 부드럽게 처리하기

app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt, app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
=> #202 [목표관리] 백버튼으로 클릭시 포커스 사라지지 않는것 수정

app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
=> #204 [목표관리] 목표관리화면 백버튼 눌렀을때 튕기는거 잡기 + 백버튼눌렀을시 대기방으로 넘어지않던 버그 해결

app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt
=> #204 [목표관리] onAttach 두개 있던 오류 잡기

app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt, app/src/main/java/com/spark/android/ui/timer/viewmodel/TimerStartViewModel.kt
=> #199 [타이머] 타이머 코드 리팩토링 

app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
=>  #208 [타이머] 타이머 코드 MVVM 리팩토링

app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt
=> #200 [홈_메인] diffutil로 리팩토링

app/src/main/res/layout/fragment_home_main.xml
=> #211 [홈_메인] 로딩뷰 위치조정

app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt
#222 
습관방 스파크 보내기
- [x] 스파크 보내기 버튼 여러번 클릭 불가능하게 수정
=> [습관방] 스파크 보내기 버튼 여러 차례 클릭 불가능하도록 수정

app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt, app/src/main/res/layout/fragment_input_code_dialog.xml
=> #220 [방 생성] 코드로 입장 edit text 밑줄색상 조건 일치시키기

app/src/main/java/com/spark/android/ui/main/MainActivity.kt
=> #227 [홈_메인] 홈플로팅 버튼 눌렀다가 닫았을때 종종 흰색으로 바뀌는 오류수정

app/src/main/java/com/spark/android/ui/main/MainActivity.kt
=> #230 [홈_메인] fab열려있을시 백버튼 처리(fab 닫도록 처리)

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/adapter/HabitRecyclerViewAdapter.kt
=> #222 [습관방] 리사이클러뷰 ListAdapter 리팩토링

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
=> #238 [습관방] 습관방 리사이클러뷰 초기화 오류 수정

app/src/main/java/com/spark/android/data/remote/entity/response/StorageResponse.kt, app/src/main/res/layout/item_storage_complete_list.xml, app/src/main/res/layout/item_storage_incomplete_list.xml, app/src/main/res/layout/item_storage_progressing_list.xml
=> #240 [보관함] 총 스파크 수 필드명 수정

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt, app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt
=> #225 [습관방] 오늘의 인증 쉴래요, 고민중 선택 시 데이터 새로고침 구현

app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/fragment_home_main.xml, app/src/main/res/layout/fragment_storage_complete.xml, app/src/main/res/layout/fragment_storage_incomplete.xml, app/src/main/res/layout/fragment_storage_progressing.xml
- #247 
#247 홈, 피드, 보관함
#247 
- 홈, 피드, 보관함 엠티뷰 위치 통일
=> [엠티뷰] 홈, 피드, 보관함 엠티뷰 위치 통일

app/src/main/AndroidManifest.xml, app/src/main/java/com/spark/android/data/remote/entity/response/PhotoCollectionResponse.kt, app/src/main/res/layout/item_photo_collection_list.xml
#256 
인증사진 모아보기 
- PhotoCollection Response에 timerRecord 추가
=> #256 [refactoring] 타이머 인증시 인증사진 모아보기에 타이머 시간 추가

app/src/main/java/com/spark/android/util/MultiPartResolver.kt
- #263 
#263 사진 관련 서버 통신 부분
#263
- 서버에 이미지 보낼 때 720픽셀 기준 초과일 시 720으로 리사이징, 이하일시 원본 파일 보내기
- 만약 1:1이 아닌경우 짧은 쪽을 720으로 설정하기
=> #263 [feat] 이미지 리사이징 관련 작업

app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt, app/src/main/java/com/spark/android/util/DialogUtil.kt, app/src/main/res/values/strings.xml
=> #265 [방 만들기] 습관방 생성 인증방식 선택 다이얼로그 추가 

app/src/main/java/com/spark/android/SparkMessagingService.kt
- #278
- #278 인증완료알림
- 이미지 유효하지 않을 시 기본 사진으로 알림 띄우도록 설정 수정
=> [인증완료알림] 이미지 유효하지 않을 시 기본 사진으로 알림 띄우도록 설정 수정

app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/adapter/WaitingRoomRecyclerViewAdapter.kt
=> #285 [대기방] 대기방 인원목록 리사이클러뷰 diffutil 리펙토링

app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/checkroom/CheckRoomFragment.kt, app/src/main/java/com/spark/android/util/AnimationUtil.kt
#287 
대기방,방만들기(중간페이지) 
- 중복터치 방지
- 애니메이션 onpause에서 cancel해서 튕김방지
=> #287 [대기방,방만들기] 코드복사 버튼 중복터치 막기 및 액티비티 종료시 애니메이션 같이 종료시켜 튕김현상 방지 작업

app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/checkroom/CheckRoomFragment.kt, app/src/main/res/values/strings.xml
#289 
방생성 
- 방생성 다이얼로그 텍스트 수정
- 대기방 및 방생성 체크 애니메이션 관련 버그 fix
=> #289 [방생성] 방생성 다이얼로그 텍스트 내용 수정 + onpause에서 애니메이션 종료관련 버그 fix

app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt, app/src/main/java/com/spark/android/util/DialogUtil.kt, app/src/main/res/values/strings.xml
#273 
#273 습관방 쉴래요 다이얼로그
- 쉴래요 사용하기 다이얼로그 추가
=> #273 [습관방] 쉴래요 사용하기 다이얼로그 추가

app/src/main/AndroidManifest.xml, app/src/main/java/com/spark/android/SparkMessagingService.kt, app/src/main/res/xml/data_extraction_rules.xml
- #298
- #299 
#298, #299 전체 및 푸쉬알림
- manifest 속성 수정 및 추가
- 푸쉬알림 카테고리별 채널아이디 통일
=> #298, #299 [전체 및 푸쉬알림] 앱 재설치 시 발생하는 에러들 해결

app/src/main/res/drawable/ic_watitng_room_extra_menu.xml, app/src/main/res/layout/fragment_waiting_room.xml, app/src/main/res/values/strings.xml
#297 
대기방 
- 더보기 버튼추가
- 인원 목록 텍스트 변경
=> #297 [대기방] 대기방 더보기 추가

app/src/main/res/layout/activity_habit_goal_manage.xml
#307 
습관방 목표 관리 뷰 
- 나의 목표 수정 뷰 수정완료 버튼 섀도우 삭제
=> #307 [습관방] 나의 목표 수정 뷰 수정완료 버튼 섀도우 삭제

app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt, app/src/main/java/com/spark/android/util/DialogUtil.kt, app/src/main/res/layout/fragment_waiting_room_bottom_sheet.xml, app/src/main/res/values/strings.xml
=> #304 [대기방] 대기방 방나가기 다이얼로그 서버 + 홈 토스트 빼고 완료

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesHomeDataSource.kt, app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesHomeDataSourceImpl.kt, app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesWaitingRoomDataSource.kt, app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesWaitingRoomDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/datasource/RemoteWaitingRoomDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/RemoteWaitingRoomDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/WaitingRoomInfoRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/DeleteRoomService.kt, app/src/main/java/com/spark/android/data/remote/service/LeaveRoomService.kt, app/src/main/java/com/spark/android/di/LocalDataSourceModule.kt, app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt, app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt, app/src/main/res/layout/fragment_home_main.xml, app/src/main/res/layout/fragment_waiting_room_bottom_sheet.xml, app/src/main/res/values/strings.xml
#312 
대기방,홈_메인 
- 방나가기 삭제하기 기능구현
- 홈 토스트 메세지 구현
=> #312 [대기방,홈_메인] 방 나가기 방 삭제하기 기능 구현 및 홈에서 토스트 메세지 띄우기

app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/joincode/inputcode/InputCodeFragmentDialog.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt
#316 
방입장_코드 입력
- 다이얼로그 끄기 
-  fab 닫기
=> #316 [방입장_코드 입력] 백스택에 다이얼로그 ,fab 켜져있는거 끄기

app/src/main/res/layout/fragment_check_room.xml
=> #318 [방생성] 습관방 생성 확인 뷰 로티 추가

app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/HomeHabitRoomFinishService.kt, app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/home/adapter/HomeRecyclerViewAdapter.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt
=> #322 [홈_메인] 완료,실패방 지옥보내기 api붙이기 완료

app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/entity/response/ProfileResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/ProfileService.kt, app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt, app/src/main/res/layout/fragment_my_page_main.xml
- #326
#326 마이페이지
-  마이페이지 관련 Api 정의
-  마이페이지 관련 서버 연결
-  마이페이지 뷰모델 생성 후 데이터 바인딩
- Glide placeholder, error 처리
=> #326 [마이페이지] 마이페이지 기능 및 서버 연결

app/src/main/java/com/spark/android/SparkMessagingService.kt, app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/ProfileDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/ProfileRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/ProfileRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/ProfileService.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileViewModel.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageActivity.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt, app/src/main/java/com/spark/android/util/ImageProvider.kt, app/src/main/java/com/spark/android/util/MultiPartResolver.kt, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/navigation/auth_nav_graph.xml, app/src/main/res/navigation/my_page_nav_graph.xml
- #327
#327 프로필 수정
- 프로필 수정 화면에서 현재 프로필 띄우기
- 프로필 이미지, 닉네임 플레이스 홀더 처리
- 프로필 수정 관련 Api 정의
- 프로필 수정 서버 연결
- 프로필 수정 완료 시 마이페이지로 화면 이동 구현
=> #327 [프로필 수정] 프로필 수정 기능 및 서버 연결

app/src/main/java/com/spark/android/data/remote/datasource/AlarmSettingDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/AlarmSettingDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/entity/response/AlarmSettingResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/AlarmSettingService.kt, app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingFragment.kt, app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingViewModel.kt, app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt, app/src/main/res/layout/fragment_alarm_setting.xml
- Closes #328
#328 알림 설정 화면
- 알림 설정 관련 Api 정의
- 알림 설정 서버 연결
- 토글로 알림 on/off 설정
=> #328 [알림 설정] 알림 설정 기능 및 서버 연결 

app/build.gradle, app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt, app/src/main/res/values/strings.xml
- Closes #336
#336 마이페이지 문의하기 
- 문의하기 클릭 시 메일 앱 연결
=> #336 [문의하기] 메일 앱 연결

app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt
=> #338 [홈_메인] 완료,실패방 다이얼로그 진행후 방목록 새로고침 하기

app/src/main/java/com/spark/android/data/remote/service/PhotoMainService.kt, app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt
#261 
대표이미지 변경 창
- PATCH Retrofit Interface
=> #261 [feat] 대표이미지 창 PATCH Retrofit interface 만듦

app/src/main/java/com/spark/android/ui/home/finishroomdialog/FinishRoomDialogFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
=> #348 [다이얼로그] 다이얼로그 마진값 수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/spark/android/ui/alarmcenter/AlarmCenterActivity.kt, app/src/main/java/com/spark/android/ui/alarmcenter/NoticeAlarmFragment.kt, app/src/main/java/com/spark/android/ui/alarmcenter/SparkActivityAlarmFragment.kt, app/src/main/res/drawable/ic_alarm_circle_sticker.xml, app/src/main/res/layout/activity_alarm_center.xml, app/src/main/res/layout/fragment_notice_alarm.xml, app/src/main/res/layout/fragment_spark_activity_alarm.xml, app/src/main/res/layout/item_alarm_list.xml, app/src/main/res/layout/item_spark_activity_alarm.xml, app/src/main/res/values/strings.xml
- Closes #341
#341 알림센터
- 알림 센터 레이아웃
- 알림 리스트 레이아웃
=> #341 [알림센터] 알림 센터 레이아웃 및 알림 리스트 레이아웃 제작

app/src/main/java/com/spark/android/data/remote/RetrofitBuilder.kt, app/src/main/java/com/spark/android/data/remote/service/PhotoMainService.kt, app/src/main/java/com/spark/android/ui/onboarding/OnBoardingActivity.kt, app/src/main/java/com/spark/android/ui/storage/adapter/PhotoMainPickRvAdapter.kt, app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoMainPickActivity.kt, app/src/main/java/com/spark/android/ui/storage/viewmodel/PhotoViewModel.kt, app/src/main/res/layout/activity_on_boarding.xml
#340 
#340 대표사진 선택창
-  완료버튼 onClickListener
- patch 구현
=> #340 [대표사진 선택창] 완료버튼 누르면 서버에 patch 기능 구현 

app/src/main/java/com/spark/android/ui/alarmcenter/alarms/ActivityAlarmFragment.kt, app/src/main/java/com/spark/android/ui/alarmcenter/alarms/ServiceAlarmFragment.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageMainFragment.kt, app/src/main/res/layout/fragment_alarm_setting.xml, app/src/main/res/layout/fragment_my_page_main.xml, app/src/main/res/layout/fragment_sign_in.xml, app/src/main/res/layout/fragment_withdrawal.xml, app/src/main/res/values/strings.xml
- Closes #368
#368 마이페이지, 로그인
- 마이페이지 약관 및 정책, 오픈소스 링크 연결
- 로그인 이용약관, 개인정보처리방침 연결
=> [마이페이지, 로그인] 약관 및 정책, 오픈소스 라이선스 링크 연결

app/src/main/java/com/spark/android/data/remote/LocalPreferences.kt, app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt, app/src/main/java/com/spark/android/util/DialogEditTextUtil.kt, app/src/main/res/layout/dialog_edit_text_util.xml
=> #362 [습관방] 습관방 나가기 후 홈 화면으로 이동 적용

app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt, app/src/main/res/drawable/dot_indicator_dot_selected.xml, app/src/main/res/drawable/dot_indicator_dot_unselected.xml, app/src/main/res/layout/fragment_user_guide_dialog.xml
=> #374 [습관방] 눈물의 닷 인디케이터 만들기 완료

app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSource.kt, app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt, app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt, app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt
- Closes #370
#370 스플래시
- 스플래시에 도어벨 api 연결
(도어벨 Api를 스플래시에도 붙여서
소셜아이디 내부에 없으면 카카오 로그인 화면으로 넘어가고
소셜아이디 내부에 있으면 access토큰 갱신 후 홈으로 넘어가기)
=> #370 [스플래시] 도어벨 api 연결

app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/FeedDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/entity/request/FeedReportRequest.kt, app/src/main/java/com/spark/android/data/remote/entity/response/FeedResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/FeedService.kt, app/src/main/java/com/spark/android/ui/feed/FeedBottomSheet.kt, app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt, app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt, app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt, app/src/main/java/com/spark/android/ui/feedreport/FeedReportViewModel.kt, app/src/main/java/com/spark/android/util/EditTextUtil.kt, app/src/main/res/layout/activity_feed_report.xml, app/src/main/res/layout/item_feed_content.xml, app/src/main/res/values/strings.xml
- Closes #381 
#381 피드 신고하기
- 피드 게시물 아이템 타인/자신 게시물에 따라 레이아웃 적용
- 피드 신고하기 기능 구현
- 피드 신고하기 서버 연결
=> #381 [피드] 신고하기 기능 및 서버 연결

app/src/main/res/values/strings.xml
#389 
대기방 
- string 수정완료
- Closed #389
=> #389 [대기방] 대기방 나의 목표멘트 수정 완료

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt, app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt, app/src/main/res/layout/bottom_sheet_habit_more.xml, app/src/main/res/layout/fragment_user_guide_dialog.xml, app/src/main/res/values/strings.xml
- Closed #392 , #393 
습관방 유저가이드
-더보기 바텀시트에 유저가이드 추가
-유저가이드 진입지점 분기처리
=> #392,393 [습관방] 더보기 바텀시트에 유저가이드 추가,유저가이드 진입지점 분기처리 (버튼visibility + 백버튼 처리)

app/src/main/res/values/strings.xml
- Closed #405 
방_생성 인증방식 선택  
- 텍스트 수정
=> #405 [방_생성] 인증방식 선택 뷰 문구 수정

app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSource.kt, app/src/main/java/com/spark/android/data/local/datasource/LocalPreferencesDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/AlarmSettingRepositoryImpl.kt, app/src/main/java/com/spark/android/di/RepositoryModule.kt, app/src/main/java/com/spark/android/ui/alarmsetting/AlarmOnOff.kt, app/src/main/java/com/spark/android/ui/alarmsetting/AlarmSettingViewModel.kt, app/src/main/java/com/spark/android/ui/mypage/MyPageViewModel.kt, app/src/main/java/com/spark/android/ui/withdrawal/WithdrawalViewModel.kt, app/src/main/res/layout/fragment_alarm_setting.xml, app/src/main/res/values/strings.xml
- Closes #408
- #408 알림 설정
- 리마인드 알림 워딩 수정(21시 -> 22시)
- 알림 on/off 스위치 플로우 수정(설정된 값으로 바로 볼 수 있도록)
- 알림 on/off 값 로컬 저장하기 (로그인 후 첫 저장 위치 : 알림 설정 화면 처음 들어갔을 시 값들 저장 후 알림 설정 로컬 저장 여부 값 true로 설정)
- 로그아웃/회원탈퇴 시 모두 알림 설정 로컬 저장 여부 값 false로 설정
=> [알림 설정] 워딩 수정 및 스위치 플로우 수정

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitMoreBottomSheet.kt, app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt, app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
#301 
#301 습관방 
- 뷰모델 라이브 데이터 써서 수정
=> #301 [습관방] 쉴래요 누르면 홈 화면으로 나가지는 오류 수정

app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt, app/src/main/res/layout/fragment_profile.xml
- Closes #411 
- #411 프로필, 로그인
- 프로필 수정 : 버튼 이미지 수정
- 소셜 로그인 : 약관 링크 연결
=> #411 [프로필, 로그인] 레이아웃 수정, 링크 연결, 기능 확인

.idea/deploymentTargetDropDown.xml, app/build.gradle, app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInViewModel.kt, app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt, app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt
- Closes #214 
- #214 회원가입
- 프로필 화면 입력 중 돌아가기 버튼 활성화
=> #214 [회원가입_프로필입력] 회원가입 프로필 화면 입력 중 돌아가기 버튼 활성화

app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt, app/src/main/java/com/spark/android/util/SendSparkToast.kt, app/src/main/res/layout/activity_habit_send_spark.xml
=> #416 [습관방] 스파크 보내기 QA 수정

app/src/main/java/com/spark/android/ui/habit/userguide/UserGuideFragmentDialog.kt, app/src/main/res/drawable/dot_indicator_dot_unselected.xml, app/src/main/res/layout/fragment_user_guide_dialog.xml, app/src/main/res/values/strings.xml
#421 
#421 습관방
- 습관방 더보기 바텀시트 순서, 문구 변경_ ‘나의 목표 관리 > 습관방 이용 팁 > 방 나가기’로 변경
- 습관방 가이드 오탈자 수정 2개
- 습관방 시간과 목표에서 아무 글자도 없을 경우, 보여지는 문구 수정
- 습관방 이용 가이드 인디케이터 어색함 수정
=> #421 [습관방] 습관방 QA 내용 수정

app/src/main/res/layout/fragment_home_main.xml
- Closed #424 
홈_메인 
-xml 순서변경
=> #424 [홈_메인] 홈 토스트 메시지 가려지는 현상 수정

app/src/main/res/values/strings.xml
- Closed #419 
방_생성 _인증_방식_선택 
- 완료버튼 문구수정
=> #419 [방_생성] 방생성 인증 방식 확인 다이얼로그 완료버튼 문구 수정

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/spark/android/data/remote/entity/response/WaitingRoomInfoResponse.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt, app/src/main/res/layout/fragment_waiting_room.xml, app/src/main/res/layout/item_waiting_room_recyclerview.xml
- Closed #428 
대기방 
- 인원목록 업데이트 수정
- 대기방 닉네임 길이조정
=> #428 [대기방] 인원목록 업데이트시 함께하는 스파커 수 수정 안되는 부분 수정, 스파커 닉네임 길이조정

app/src/main/res/values/strings.xml
- Closed #430 
대기방 
- 습관방 만들기 버튼 텍스트 수정
- 다이얼로그 텍스트 띄워쓰기 수정
=> #430 [대기방] 습관방 만들기 버튼 텍스트 수정,다이얼로그 텍스트 띄워쓰기 수정

app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt
- Closed #432 
홈_메인 
- 홈_메인 토스트 메시지 방이름 너무 길때  생략
=> #432 [홈_메인] 대기방 삭제 홈 토스트 메시지 너무 길면 생략

app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt, app/src/main/java/com/spark/android/ui/setpurpose/viewmodel/SetPurposeViewModel.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt
- Closed #439 
목표_작성 
- 데이터 업데이트
=> #439 [목표_작성] 기존 작성된 목표 다시 목표작성 프래그먼트에 진입 했을때 edittext에 넣어주기

app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt
=> #423 [대기방] 대기방 생성후 홈으로 이동하는 부분 습관방으로 이동하도록 수정

app/src/main/res/layout/fragment_name_setting.xml, app/src/main/res/layout/fragment_select_confirm_method.xml, app/src/main/res/values/strings.xml
- Closed #445 
- Closed #446 
방생성 
- 폰트 사이즈,문구수정
- 버튼 글자수에 의한 활성화 정리
=> #445,446 [방생성] 대기방 생성_인증방식 폰트 사이즈 수정+ 버튼 문구수정, 습관방생성_방이름 설정뷰 버튼 활성화 관계

app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt
- Closed #454
#454 피드 신고하기
- 뒤로가기 활성화
- 텍스트 필드 작성 중 여백 클릭 시 키보드 없애기
=> #454 [신고하기] 뒤로가기 활성화 및 텍스트 필드 관련 기능 추가

app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt
- Closed #456
#456 신고하기 - 피드
- 신고하기 버튼 클릭 후 & 신고하기 중 뒤로가기 클릭 후 피드 뷰로 돌아오도록 개선
=> #456 [feat] 신고하기 버튼 클릭 후 & 신고하기 중 뒤로가기 클릭 후 피드 뷰로 돌아오도록 개선

app/build.gradle, app/src/main/java/com/spark/android/data/remote/repository/FeedRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/FeedRepositoryImpl.kt, app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt, app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt, app/src/main/java/com/spark/android/ui/feed/adapter/FeedAdapter.kt, app/src/main/res/layout/fragment_feed.xml
- Closed #459
#459 피드 
- 피드 최상단을 아래로 스와이프 할 경우 피드 리스트 갱신
=> #459 [피드] 리프레시 적용

app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt, app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt, app/src/main/java/com/spark/android/ui/home/HomeMainFragment.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/fragment_home_main.xml
- Closed #459, 461
#459 피드
#461 홈
- 피드 리프레시 할 때 스크롤 감지되어 리스트 중복으로 받아오는 문제 해결
- 홈 상단에서 하단으로 스와이프 시 홈 습관방 리스트 갱신 적용
=> #461 [홈] 리프레시 적용

app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/RemoteHomeDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/entity/response/HomeNoticeRedDotResponese.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/HomeRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/HomeNoticeRedDotService.kt, app/src/main/java/com/spark/android/di/RemoteDataSourceModule.kt, app/src/main/java/com/spark/android/di/RetrofitServiceModule.kt, app/src/main/java/com/spark/android/ui/home/viewmodel/HomeMainViewModel.kt, app/src/main/res/drawable/ic_home_notice_red_dot.xml, app/src/main/res/layout/fragment_home_main.xml
- Closed #458 
홈_메인 
- 빨콩스 완료스
=> #458 [홈_메인] 빨콩스 완료스

app/src/main/java/com/spark/android/util/FirebaseLogUtil.kt
- Closed #467
#467 전체
- GA 트래킹 심는 Util 함수 제작
=> #467 [feat] GA 트래킹 심는 Util 함수 제작

app/src/main/java/com/spark/android/ui/joincode/JoinCodeActivity.kt, app/src/main/java/com/spark/android/ui/joincode/viewmodel/JoinCodeViewModel.kt, app/src/main/java/com/spark/android/ui/makeroom/selectconfirmmethod/SelectConfirmMethodFragment.kt, app/src/main/java/com/spark/android/ui/setpurpose/SetPurposeFragment.kt, app/src/main/java/com/spark/android/ui/setpurpose/viewmodel/SetPurposeViewModel.kt, app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/ui/waitingroom/bottomsheet/WaitingRoomFragmentBottomSheet.kt, app/src/main/java/com/spark/android/ui/waitingroom/makeroomcheckdialog/MakeRoomCheckFragmentDialog.kt, app/src/main/java/com/spark/android/ui/waitingroom/viewmodel/WaitingRoomViewModel.kt
- Closed #367 
- Closed #437 
대기방,홈,습관방 
- EventWrapper관련 리펙토링
=> #367,437 [fix] EventWrapper로 대기방 생성 삭제. onSuccess에 finish 달기

app/src/main/java/com/spark/android/util/FirebaseLogUtil.kt
- Closed #472
#472 전체
- GA 클릭 이벤트 측정 방법 수정
=> #472 [feat] GA 클릭 이벤트 측정 방법 수정

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/util/BindingAdapters.kt
- Closed #474 
#474 습관방 - 나의 목표 관리
- 나의 목표 관리 비정상 종료 수정
=> #474 [fix] 나의 목표 관리 비정상 종료 수정

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt
- Closed #476 
#476 습관방 생명감소 알림
- 함수 호출 시점 변경
=> #476 [fix] 습관방 생명 감소 알림 수정

app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/java/com/spark/android/ui/storage/StorageCompleteFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageIncompleteFragment.kt, app/src/main/java/com/spark/android/ui/storage/StorageProgressingFragment.kt, app/src/main/java/com/spark/android/ui/storage/adapter/CompleteVpAdapter.kt, app/src/main/java/com/spark/android/ui/storage/adapter/IncompleteVpAdapter.kt, app/src/main/java/com/spark/android/ui/storage/adapter/ProgressingVpAdapter.kt, app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoCollectionActivity.kt, app/src/main/java/com/spark/android/ui/storage/photo/StoragePhotoMainPickActivity.kt, app/src/main/java/com/spark/android/ui/storage/viewmodel/StorageViewModel.kt, app/src/main/res/navigation/main_nav_graph.xml
- Closed #400 
#400 
- 인증사진 모아보기에서 뒤로갈 시  해당 탭의 첫째 아이템 등장
- 각 탭 클릭시 탭의 첫째 아이템 등장
=> #400 [보관함] 뒤로가기 로직 수정 

app/src/main/java/com/spark/android/SparkMessagingService.kt, app/src/main/java/com/spark/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/spark/android/ui/auth/signin/SignInFragment.kt, app/src/main/java/com/spark/android/ui/feed/FeedViewModel.kt, app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt, app/src/main/java/com/spark/android/ui/share/InstaShareDialogFragment.kt, app/src/main/java/com/spark/android/util/FirebaseLogUtil.kt
- Closed #480 
- 소셜로그인
- 회원가입
- 인증 후 다이얼로그
- 피드
- 푸시 알림
- GA를 위한 트래킹 코드 심기
-  소셜로그인
-  회원가입
-  인증 후 다이얼로그
-  피드
-  푸시 알림
=> #480 [트래킹] GA 트래킹 연주 부분~!

app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitLifeLessDialogFragment.kt, app/src/main/res/layout/dialog_habit_life_less.xml
- Closed #482 
#482 습관방 
- 습관방 생명 감소 알림 개수 오류 수정
=> #482 [fix] 습관방 생명 감소 알림 개수 오류 수정

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/spark/android/util/AnimationUtil.kt
- Closed #485 
목표설정
- 애니메이션 속도변경
=> #485 [목표 설정] 애니메이션 속도변경

app/src/main/java/com/spark/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt, app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt, app/src/main/java/com/spark/android/ui/habit/adapter/HabitSendSparkRecyclerViewAdapter.kt, app/src/main/java/com/spark/android/ui/timer/TimerStartActivity.kt
- Closed #487 
#487 습관방, 습관방 인증하기, 습관방 스파크 보내기, 습관방 고민중, 스톱워치
- 습관방
- 습관방 인증하기
- 습관방 스파크 보내기
- 습관방 고민중
- 스톱워치
=> #487 [트래킹] GA 트래킹 재훈

app/src/main/java/com/spark/android/ui/habit/HabitTodayBottomSheet.kt, app/src/main/java/com/spark/android/ui/habit/viewmodel/HabitViewModel.kt
- Closed #489 
#489 습관방
- 고민중 / 쉴래요 클릭 후 리프레시 적용 안되었을 때, 다시 누르면 홈 화면으로 이동 혹은 비정상 종료 오류 해결
=> #489 [fix] 고민중 / 쉴래요 클릭 비정상 종료 오류 해결

app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSource.kt, app/src/main/java/com/spark/android/data/remote/datasource/AuthDataSourceImpl.kt, app/src/main/java/com/spark/android/data/remote/entity/response/VersionResponse.kt, app/src/main/java/com/spark/android/data/remote/repository/AuthRepository.kt, app/src/main/java/com/spark/android/data/remote/repository/AuthRepositoryImpl.kt, app/src/main/java/com/spark/android/data/remote/service/AuthService.kt, app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt, app/src/main/java/com/spark/android/ui/intro/IntroViewModel.kt, app/src/main/java/com/spark/android/ui/intro/VersionUpdateState.kt, app/src/main/java/com/spark/android/util/DialogUtil.kt, app/src/main/res/values/strings.xml
- Closed #479
#479 스플래시
-  강제 업데이트 안내 다이얼로그 추가
- 업데이트하기 터치 시 스토어 링크로 연결
- 다이얼로그 외부 영역 터치 막기
- 서버 통신 연결
=> #479 [스플래시] 강제 업데이트 안내 다이얼로그 추가

app/src/main/res/values/strings.xml
- Closed #500
#500 로그인, 마이페이지
- 이용약관, 개인정보처리방침, 약관 및 정책, 오픈소스 링크 수정
=> #500 [modify] 이용약관, 개인정보처리방침, 약관 및 정책, 오픈소스 링크 수정

app/src/main/java/com/spark/android/ui/feed/FeedFragment.kt, app/src/main/java/com/spark/android/ui/feedreport/FeedReportActivity.kt, app/src/main/java/com/spark/android/ui/main/MainActivity.kt, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/navigation/main_nav_graph.xml, app/src/main/res/values/strings.xml
- Closed #504
#504 피드
- 피드 신고 완료 시 토스트 애니메이션 띄우기
=> #504 [feat] 피드 신고 완료 시 토스트 애니메이션 띄우기

app/src/main/java/com/spark/android/ui/habit/adapter/HabitSendSparkRecyclerViewAdapter.kt
- Closed #491 
#491 습관방 스파크 보내기 
- 터치 영역 버튼 한 번 더 눌러야 눌러지는 현상 개선
=> #491 [fix] 터치 영역 버튼 한 번 더 눌러야 눌러지는 현상 개선

app/build.gradle, app/proguard-rules.pro, app/src/main/java/com/spark/android/ui/habit/HabitSendSparkBottomSheet.kt, build.gradle
=> Revert "#510 [난독화] release 모드일 때 난독화 설정"

app/build.gradle, app/proguard-rules.pro, app/release/output-metadata.json
- Closed #510
#510 
- 서버 통신 위한 request, response 파일 제외하고 난독화 설정
- 카카오 로그인을 위해 카카오 SDK를 제외하고 난독화 설정
=> #510 [난독화] release 모드일 때 난독화 설정

app/src/main/java/com/spark/android/ui/waitingroom/WaitingRoomFragment.kt, app/src/main/java/com/spark/android/util/AnimationUtil.kt
=> #516 [대기방] 새로고침 버튼 비활성화 오류 막기

app/src/main/java/com/spark/android/ui/habit/HabitSendSparkActivity.kt
- Closed #511 
#511 습관방
- <메시지 직접 입력하기>버튼 선택후 배경선택하여 취소 시 스파크 보내기 다른 버튼들 보임 현상 개선
=> #511 [습관방] 스파크 보내기 QA

app/src/main/java/com/spark/android/ui/intro/IntroActivity.kt
- Closed #525
#525 스플래시  
- 버전 확인 후 강제 업데이트 해당 여부에 따라 이후 동작 시작 여부 설정
=> #525 [fix] 버전 확인 후 강제 업데이트 해당 여부에 따라 이후 동작 시작 여부 설정

app/src/main/java/com/teamsparker/android/ui/auth/profile/ProfileBottomSheet.kt, app/src/main/java/com/teamsparker/android/ui/auth/profile/ProfileFragment.kt, app/src/main/java/com/teamsparker/android/ui/certify/CertifyActivity.kt, app/src/main/java/com/teamsparker/android/ui/certify/CertifyBottomSheet.kt, app/src/main/java/com/teamsparker/android/ui/certify/viewmodel/CertifyViewModel.kt, app/src/main/java/com/teamsparker/android/ui/feedreport/FeedReportActivity.kt, app/src/main/java/com/teamsparker/android/ui/intro/IntroActivity.kt, app/src/main/java/com/teamsparker/android/ui/intro/IntroViewModel.kt, app/src/main/java/com/teamsparker/android/ui/onboarding/OnBoardingActivity.kt, app/src/main/java/com/teamsparker/android/ui/share/InstaActivity.kt, app/src/main/java/com/teamsparker/android/util/BindingAdapters.kt, app/src/main/res/layout/activity_feed_report.xml, app/src/main/res/layout/activity_join_code.xml, app/src/main/res/layout/fragment_check_room.xml, app/src/main/res/layout/fragment_select_confirm_method.xml, app/src/main/res/layout/fragment_waiting_room.xml
- Closed #532, #533, #534
#532, #533 카메라
#534 대기방입장, 습관인증방식설정, 대기방, 초대코드입력후입장, 신고하기
- 카메라 회전시 uri 데이터 잃는 문제 해결
- 인증하기에서 용량이 큰 고화질 이미지 로드 시 발생하는 에러 해결
- 카메라로 인증 시 이미지 저장되던 것 저장 안되도록 구현
- 스크롤뷰 적용을 통해 다양한 기기 화면 대응
=> Hotfix 1.0.1

app/build.gradle
- Closed #536
x
- 버전코드, 버전네임 수정
=> #536 [chore] 버전코드, 버전네임 수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/teamsparker/android/SparkApplication.kt, app/src/main/java/com/teamsparker/android/SparkMessagingService.kt, app/src/main/java/com/teamsparker/android/ui/intro/IntroActivity.kt, app/src/main/java/com/teamsparker/android/ui/main/MainActivity.kt, app/src/main/java/com/teamsparker/android/util/CheckForeground.kt, app/src/main/java/com/teamsparker/android/util/NotificationCategory.kt
- Closed #540
#540 푸쉬 알림 클릭 시 화면 이동 구현
- Foreground, Background 감지 싱글톤 생성
- 푸쉬알림 클릭 시 카테고리 별, Foreground/Background에 따라 화면 이동 구현
=> #540 [feat] 푸쉬 알림 클릭 시 화면 이동 구현

README.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/teamsparker/android/SparkApplication.kt, app/src/main/java/com/teamsparker/android/SparkMessagingService.kt, app/src/main/java/com/teamsparker/android/ui/intro/IntroActivity.kt, app/src/main/java/com/teamsparker/android/ui/main/MainActivity.kt, app/src/main/java/com/teamsparker/android/util/CheckForeground.kt, app/src/main/java/com/teamsparker/android/util/NotificationCategory.kt
=> Release 1.0.2
